version: "3"

services:
  auth-db:
    image: postgres
    container_name: auth-db
    hostname: auth-db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth

  climsoft-db:
    image: postgres
    container_name: climsoft-db
    hostname: climsoft-db
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=climsoft


  surface-db:
    image: postgres
    container_name: surface-db
    hostname: surface-db
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=surface


  opencdms-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opencdms-server
    hostname: opencdms-server
    ports:
      - "8000:5000"
    depends_on:
      - auth-db
      - climsoft-db
      - surface-db
