version: "3"

services:
  opencdms_api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: opencdms_api
    ports:
      - "5070:5000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code/surface/api
    depends_on:
      - opencdms_surface_db
      - opencdms_mch_db
    volumes:
      - ./src:/code/src

  opencdms_surface_db:
    image: timescale/timescaledb-postgis:2.3.0-pg13
    container_name: opencdms_surface_db
    volumes:
      - ./data/shared:/data/shared
      - opencdms_surface_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    env_file:
      - .surface_db.env

  opencdms_mch_db:
    image: mysql:8.0.27
    container_name: opencdms_mch_db
    volumes:
      - opencdms_mch_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .mch_db.env

volumes:
  opencdms_surface_data:
  opencdms_mch_data:
