version: "3"

services:
  opencdms_api:
    image: opencdms_server:0.1.0
    build:
      context: .
      dockerfile: dockerfile
    container_name: opencdms_api
    ports:
      - "5070:5000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code/surface/api
    depends_on:
      - opencdms_surface_db
      - opencdms_mch_db
    volumes:
      - ./src:/code/src
    networks:
      - opencdms_server_dev_network
    command:
      [
        "uvicorn",
        "opencdms_server.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--reload",
        "--use-colors",
      ]

  opencdms_surface_db:
    image: timescale/timescaledb-postgis:2.3.0-pg13
    container_name: opencdms_surface_db
    volumes:
      - ./data/shared:/data/shared
      - opencdms_surface_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    env_file:
      - .surface_db.env
    networks:
      - opencdms_server_dev_network

  opencdms_mch_db:
    image: opencdms_mch_db
    build:
      context: .
      dockerfile: mch.dockerfile
    container_name: opencdms_mch_db
    volumes:
      - opencdms_mch_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .mch_db.env
    networks:
      - opencdms_server_dev_network

volumes:
  opencdms_surface_data:
  opencdms_mch_data:

networks:
  opencdms_server_dev_network:
