version: "3"

services:
  authdb:
    image: postgres
    container_name: authdb
    hostname: authdb
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth

  climsoftdb:
    image: mariadb:10.1
    container_name: climsoftdb
    hostname: climsoftdb
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=climsoft


  surfacedb:
    image: timescale/timescaledb-postgis:latest-pg12
    container_name: surfacedb
    hostname: surfacedb
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=surface

  mchdb:
    build:
      context: ./mch_db
      dockerfile: Dockerfile
    container_name: mchdb
    ports:
      - "23306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mch_english


  opencdms-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opencdms-server
    hostname: opencdms-server
    ports:
      - "8000:5000"
    depends_on:
      - authdb
      - climsoftdb
      - surfacedb
      - mchdb
    environment:
      - CLIMSOFT_DB_URI=mysql+mysqldb://root:password@climsoftdb/climsoft
      - AUTH_DB_URI=postgresql+psycopg2://postgres:password@authdb/auth
      - SURFACE_DB_NAME=surface
      - SURFACE_DB_USER=postgres
      - SURFACE_DB_PASSWORD=password
      - SURFACE_DB_HOST=surfacedb
      - SURFACE_DB_PORT=5432
      - MCH_DB_PORT=3306
      - MCH_DB_HOST=mchdb
      - MCH_DB_NAME=mch_english
      - MCH_DB_PASSWORD=password
      - MCH_DB_USER=root

